### ISSUE TITLE
dtls_session_cleanup panic

### ISSUE THREAD

**Issue by porjo** [pions/webrtc#109]
When calling `RTCPeerConnection.Close()` I'm seeing this:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3d pc=0x7f7f003a39dd]

runtime stack:
runtime.throw(0x7a0bd1, 0x2a)
	/usr/lib/golang/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:372 +0x28e

goroutine 114 [syscall]:
runtime.cgocall(0x6cf2e0, 0xc42044cd80, 0xc42016c040)
	/usr/lib/golang/src/runtime/cgocall.go:128 +0x64 fp=0xc42044cd50 sp=0xc42044cd18 pc=0x4048d4
github.com/pions/webrtc/internal/dtls._Cfunc_dtls_session_cleanup(0x7f7ed40061c0, 0x7f7ef0000c50, 0x7f7ed4000b20)
	_cgo_gotypes.go:241 +0x45 fp=0xc42044cd80 sp=0xc42044cd50 pc=0x69b195
github.com/pions/webrtc/internal/dtls.(*State).Close.func1(0x7f7ed40061c0, 0x7f7ef0000c50, 0x7f7ed4000b20)
	/home/ian/go/src/github.com/pions/webrtc/internal/dtls/dtls.go:90 +0xc4 fp=0xc42044cdb8 sp=0xc42044cd80 pc=0x69c8e4
github.com/pions/webrtc/internal/dtls.(*State).Close(0xc420303f60)
	/home/ian/go/src/github.com/pions/webrtc/internal/dtls/dtls.go:90 +0x41 fp=0xc42044cde0 sp=0xc42044cdb8 pc=0x69bb61
github.com/pions/webrtc/internal/network.(*Manager).Close(0xc42038e0b0)
	/home/ian/go/src/github.com/pions/webrtc/internal/network/manager.go:124 +0x93 fp=0xc42044cec0 sp=0xc42044cde0 pc=0x6abd33
github.com/pions/webrtc.(*RTCPeerConnection).Close(0xc4203069a0, 0x759480, 0xc4202a21b0)
	/home/ian/go/src/github.com/pions/webrtc/rtcpeerconnection.go:740 +0x32 fp=0xc42044ced8 sp=0xc42044cec0 pc=0x6b2f72
main.(*WebRTCPeer).Close(0xc4202e6a10, 0x796469, 0x11)
	/home/ian/go/src/github.com/porjo/babelcast/webrtc.go:28 +0x2e fp=0xc42044cf00 sp=0xc42044ced8 pc=0x6cd84e
main.(*Conn).rtcStateChangeHandler(0xc420294140, 0x6)
	/home/ian/go/src/github.com/porjo/babelcast/conn.go:215 +0x85 fp=0xc42044cf70 sp=0xc42044cf00 pc=0x6cb655
main.(*Conn).(main.rtcStateChangeHandler)-fm(0x6)
	/home/ian/go/src/github.com/porjo/babelcast/conn.go:71 +0x34 fp=0xc42044cf90 sp=0xc42044cf70 pc=0x6ce454
github.com/pions/webrtc.(*RTCPeerConnection).iceStateChange(0xc4203069a0, 0x6)
	/home/ian/go/src/github.com/pions/webrtc/rtcpeerconnection.go:803 +0x99 fp=0xc42044cfb8 sp=0xc42044cf90 pc=0x6b3439
github.com/pions/webrtc.(*RTCPeerConnection).(github.com/pions/webrtc.iceStateChange)-fm(0x6)
	/home/ian/go/src/github.com/pions/webrtc/rtcpeerconnection.go:171 +0x34 fp=0xc42044cfd8 sp=0xc42044cfb8 pc=0x6b6574
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42044cfe0 sp=0xc42044cfd8 pc=0x458201
created by github.com/pions/webrtc/pkg/ice.(*Agent).updateConnectionState
	/home/ian/go/src/github.com/pions/webrtc/pkg/ice/agent.go:164 +0x45

```
My code isn't online yet, but happy to do some local debug if required.

**Comment by trivigy** [comment]
@porjo this is under current development. Will fix it really soon. Thanks for sharing.

**Comment by porjo** [comment]
It turns out I was calling `RTCPeerConnection.Close()` more than once. Since I've fixed that I have not seen another panic.

**Comment by trivigy** [comment]
@porjo glad to hear it worked out for you. Generally speaking though, according to the spec, you should be fine calling `RTCPeerConnection.Close()` multiple times. Unfortunately we are missing a few key features still internally which probably causes this issue. Hopefully we can resolve stuff soon. Actively working on it as we speak.
