### ISSUE TITLE
crasher in codecs.VP8Packet

### ISSUE THREAD

**Issue by maxhawkins** [pions/webrtc#316]
I encountered this out of bounds panic while parsing a malformed VP8 packet.

```
panic: runtime error: slice bounds out of range

goroutine 35 [running]:
github.com/pions/webrtc/pkg/rtp/codecs.(*VP8Packet).Unmarshal(0xc0001c0060, 0xc0015017a0, 0x567, 0xd80, 0x1035, 0xc001ae6c00, 0xace)
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.0/pkg/rtp/codecs/vp8_packet.go:115 +0x18e
github.com/pions/webrtc/pkg/media/samplebuilder.(*SampleBuilder).buildSample(0xc0012da000, 0xc0001f10e3, 0xc0000a8390)
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.0/pkg/media/samplebuilder/samplebuilder.go:63 +0x103
github.com/pions/webrtc/pkg/media/samplebuilder.(*SampleBuilder).Pop(0xc0012da000, 0xc000229e58)
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.0/pkg/media/samplebuilder/samplebuilder.go:101 +0x87
main.(*Demo).handleTrack(0xc000136000, 0x4465980, 0xc0000a8380, 0xc0001e0420)
        /Users/max/projects/asciirtc/main.go:171 +0x5d2
main.(*Demo).Match.func2.1()
        /Users/max/projects/asciirtc/main.go:93 +0x45
sync.(*Once).Do(0xc0001de030, 0xc0001c7f78)
        /usr/local/Cellar/go/1.11.2/libexec/src/sync/once.go:44 +0xb3
main.(*Demo).Match.func2(0xc0001e0420)
        /Users/max/projects/asciirtc/main.go:92 +0x7b
github.com/pions/webrtc.(*RTCPeerConnection).onTrack.func1(0xc0001e8030, 0xc0001e0420, 0xc000144008)
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.0/rtcpeerconnection.go:300 +0x30
created by github.com/pions/webrtc.(*RTCPeerConnection).onTrack
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.0/rtcpeerconnection.go:299 +0xef
```

**Comment by Sean-Der** [comment]
@maxhawkins nice catch!

We have to a create a leaderboard for you, finding all these crashes. I also need to get up to speed with the fuzzing stuff you have done. Never done anything around it before.

**Comment by maxhawkins** [comment]
All my buggy code is like a fuzzer. It provides all sorts of garbled packets to test the parser code!

**Comment by maxhawkins** [comment]
Here's another one:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/pions/webrtc/pkg/rtp/codecs.(*VP8Packet).Unmarshal(0xc0000741b0, 0xc000112090,0x0, 0xc000114000, 0x0, 0xc00007ce28, 0x108c327)
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.0/pkg/rtp/codecs/vp8_packet.go:86 +0x1a3
github.com/pions/webrtc/pkg/media/samplebuilder.(*SampleBuilder).buildSample(0xc000090000, 0x3371, 0x2)
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.0/pkg/media/samplebuilder/samplebuilder.go:65 +0x103
github.com/pions/webrtc/pkg/media/samplebuilder.(*SampleBuilder).Pop(0xc000090000, 0xc000112120)
        /Users/max/go/pkg/mod/github.com/pions/webrtc@v1.2.0/pkg/media/samplebuilder/samplebuilder.go:105 +0x12d
main.main()
        /Users/max/projects/asciirtc/frag/main.go:34 +0x2dc
exit status 2
```
