### ISSUE TITLE
DTLSTransport.Stop() will hang during DTLSTransport.Start()

### ISSUE THREAD

**Issue by kixelated** [pions/webrtc#487]
Had a case where I errored out quickly, calling `defer peerConnection.Close()` to clean up after the connection. This hangs indefinitely.

[This](https://github.com/pions/webrtc/blob/43604d549197a714b83fb15cce4c226f21928f91/dtlstransport.go#L226) blocks on this [this](https://github.com/pions/webrtc/blob/43604d549197a714b83fb15cce4c226f21928f91/dtlstransport.go#L201). I didn't trace any deeper.

**Comment by kixelated** [comment]
```
goroutine 6 [chan receive]:
github.com/pions/dtls.createConn(0x1507f60, 0xc00000ec60, 0x148e5e8, 0x148e5f0, 0xc0000306c0, 0xc000026c01, 0x4, 0xc000270808, 0x18)
	/Users/lcurley/go/pkg/mod/github.com/pions/dtls@v1.2.1/conn.go:144 +0x3ad
github.com/pions/dtls.Client(...)
	/Users/lcurley/go/pkg/mod/github.com/pions/dtls@v1.2.1/conn.go:159
github.com/pions/webrtc.(*DTLSTransport).Start(0xc0001df480, 0xc000160301, 0xc000061f38, 0x1, 0x1, 0x0, 0x0)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/dtlstransport.go:200 +0x489
github.com/pions/webrtc.(*PeerConnection).SetRemoteDescription.func2(0xc00007c200, 0xc0001b2160, 0xc000026c0a, 0x4, 0xc000270808, 0x18, 0xc00026608c, 0x7, 0xc000266094, 0x5f)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/peerconnection.go:848 +0x23d
created by github.com/pions/webrtc.(*PeerConnection).SetRemoteDescription
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/peerconnection.go:822 +0xd75

goroutine 9 [select]:
github.com/pions/dtls.(*Conn).startHandshakeOutbound.func1(0xc000268c00)
	/Users/lcurley/go/pkg/mod/github.com/pions/dtls@v1.2.1/conn.go:400 +0xd8
created by github.com/pions/dtls.(*Conn).startHandshakeOutbound
	/Users/lcurley/go/pkg/mod/github.com/pions/dtls@v1.2.1/conn.go:394 +0x3f
```

**Comment by kixelated** [comment]
All goroutines just in case:

```
SIGABRT: abort
PC=0x7fffcce55bf2 m=0 sigcode=0

goroutine 7 [select]:
github.com/pions/webrtc/internal/ice.(*Conn).Read(0xc0000101b8, 0xc0002e4000, 0x2000, 0x2000, 0x148eff0, 0xc0000507c8, 0x1388d8a)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/ice/transport.go:66 +0x168
github.com/pions/webrtc/internal/mux.(*Mux).readLoop(0xc000030680)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/mux/mux.go:81 +0xda
created by github.com/pions/webrtc/internal/mux.NewMux
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/mux/mux.go:27 +0xc8

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x2d51f08, 0x72, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000122098, 0x72, 0x0, 0x0, 0x147232e)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000122080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc000122080, 0xc0000bfd80, 0xc022032fc9, 0x17cb9a0)
	/usr/local/Cellar/go/1.12/libexec/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0000a8020, 0x2372e22032fc9, 0x100000001, 0xc0000bfdc0)
	/usr/local/Cellar/go/1.12/libexec/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc0000a8020, 0xc0000bfde8, 0x10a44e6, 0x5c804e86)
	/usr/local/Cellar/go/1.12/libexec/src/net/tcpsock.go:247 +0x48
net/http.tcpKeepAliveListener.Accept(0xc0000a8020, 0xc0000bfe38, 0x18, 0xc0000d0900, 0x127ab34)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:3264 +0x2f
net/http.(*Server).Serve(0xc0000deb60, 0x1503ea0, 0xc0000a8020, 0x0, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:2859 +0x22d
net/http.(*Server).ListenAndServe(0xc0000deb60, 0x4, 0x1474fb4)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:2797 +0xe4
code.justin.tv/video/warp/server.(*Server).runHttp.func2(0xc0000aa300, 0xc0000aa420, 0xc0000deb60)
	/Users/lcurley/twitch/warp/server/server.go:53 +0xb2
created by code.justin.tv/video/warp/server.(*Server).runHttp
	/Users/lcurley/twitch/warp/server/server.go:51 +0x1bd

goroutine 25 [semacquire]:
sync.runtime_SemacquireMutex(0xc0001df484, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0001df480)
	/usr/local/Cellar/go/1.12/libexec/src/sync/mutex.go:134 +0xff
sync.(*RWMutex).Lock(0xc0001df480)
	/usr/local/Cellar/go/1.12/libexec/src/sync/rwmutex.go:93 +0x2d
github.com/pions/webrtc.(*DTLSTransport).Stop(0xc0001df480, 0x0, 0x0)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/dtlstransport.go:225 +0x4d
github.com/pions/webrtc.(*PeerConnection).Close(0xc0001b2160, 0x0, 0x1)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/peerconnection.go:1343 +0x1f4
code.justin.tv/video/warp/server.(*Connection).Run(0xc000188060, 0x15047e0, 0xc0000e2580, 0x14fbb00, 0xc000021350)
	/Users/lcurley/twitch/warp/server/connection.go:78 +0x129
code.justin.tv/video/warp/server.(*Server).handle(0xc0000aa300, 0x1503d20, 0xc0001a8000, 0xc00019a100, 0x0, 0x0)
	/Users/lcurley/twitch/warp/server/server.go:92 +0x1bf
code.justin.tv/video/warp/server.(*Server).runHttp.func1(0x1503d20, 0xc0001a8000, 0xc00019a000)
	/Users/lcurley/twitch/warp/server/server.go:38 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc0000ccf60, 0x1503d20, 0xc0001a8000, 0xc00019a000)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0000e25c0, 0x1503d20, 0xc0001a8000, 0xc00019a000)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000deb60, 0x1503d20, 0xc0001a8000, 0xc00019a000)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc0000d6d20, 0x15047e0, 0xc000184100)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:2884 +0x2f4

goroutine 66 [IO wait]:
internal/poll.runtime_pollWait(0x2d51d68, 0x72, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0001df118, 0x72, 0x2000, 0x2000, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).ReadFrom(0xc0001df100, 0xc000222000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_unix.go:219 +0x194
net.(*netFD).readFrom(0xc0001df100, 0xc000222000, 0x2000, 0x2000, 0x1059d20, 0xc000155e20, 0x2, 0x2, 0xc000155e14)
	/usr/local/Cellar/go/1.12/libexec/src/net/fd_unix.go:208 +0x5b
net.(*UDPConn).readFrom(0xc0001b6020, 0xc000222000, 0x2000, 0x2000, 0x1, 0x0, 0x0, 0xc0001ec180)
	/usr/local/Cellar/go/1.12/libexec/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc0001b6020, 0xc000222000, 0x2000, 0x2000, 0x0, 0x0, 0xc00009c9c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/net/udpsock.go:121 +0x5e
github.com/pions/webrtc/internal/ice.(*Candidate).recvLoop(0xc0001fa0b0)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/ice/candidate.go:137 +0xcf
created by github.com/pions/webrtc/internal/ice.(*Candidate).start
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/ice/candidate.go:127 +0xe9

goroutine 67 [IO wait]:
internal/poll.runtime_pollWait(0x2d51c98, 0x72, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0001df198, 0x72, 0x2000, 0x2000, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).ReadFrom(0xc0001df180, 0xc00022c000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_unix.go:219 +0x194
net.(*netFD).readFrom(0xc0001df180, 0xc00022c000, 0x2000, 0x2000, 0xc000228640, 0x100d3e9, 0x2986460, 0x65, 0xc00022c000)
	/usr/local/Cellar/go/1.12/libexec/src/net/fd_unix.go:208 +0x5b
net.(*UDPConn).readFrom(0xc0001b6030, 0xc00022c000, 0x2000, 0x2000, 0x0, 0x0, 0xc000228670, 0x1043c8c)
	/usr/local/Cellar/go/1.12/libexec/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc0001b6030, 0xc00022c000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/net/udpsock.go:121 +0x5e
github.com/pions/webrtc/internal/ice.(*Candidate).recvLoop(0xc0001fa160)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/ice/candidate.go:137 +0xcf
created by github.com/pions/webrtc/internal/ice.(*Candidate).start
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/ice/candidate.go:127 +0xe9

goroutine 71 [IO wait]:
internal/poll.runtime_pollWait(0x2d51bc8, 0x72, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0001df318, 0x72, 0x2000, 0x2000, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).ReadFrom(0xc0001df300, 0xc000232000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/internal/poll/fd_unix.go:219 +0x194
net.(*netFD).readFrom(0xc0001df300, 0xc000232000, 0x2000, 0x2000, 0xc000229e40, 0x100d3e9, 0x2985d98, 0x65, 0xc000232000)
	/usr/local/Cellar/go/1.12/libexec/src/net/fd_unix.go:208 +0x5b
net.(*UDPConn).readFrom(0xc0001b6060, 0xc000232000, 0x2000, 0x2000, 0x0, 0x0, 0xc000229e70, 0x1043c8c)
	/usr/local/Cellar/go/1.12/libexec/src/net/udpsock_posix.go:47 +0x6a
net.(*UDPConn).ReadFrom(0xc0001b6060, 0xc000232000, 0x2000, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12/libexec/src/net/udpsock.go:121 +0x5e
github.com/pions/webrtc/internal/ice.(*Candidate).recvLoop(0xc0001fa210)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/ice/candidate.go:137 +0xcf
created by github.com/pions/webrtc/internal/ice.(*Candidate).start
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/ice/candidate.go:127 +0xe9

goroutine 74 [select]:
github.com/pions/webrtc/internal/ice.(*Agent).taskLoop(0xc000208000)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/ice/agent.go:451 +0xe7
created by github.com/pions/webrtc/internal/ice.NewAgent
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/ice/agent.go:163 +0x3e8

goroutine 6 [chan receive]:
github.com/pions/dtls.createConn(0x1507f60, 0xc00000ec60, 0x148e5e8, 0x148e5f0, 0xc0000306c0, 0xc000026c01, 0x4, 0xc000270808, 0x18)
	/Users/lcurley/go/pkg/mod/github.com/pions/dtls@v1.2.1/conn.go:144 +0x3ad
github.com/pions/dtls.Client(...)
	/Users/lcurley/go/pkg/mod/github.com/pions/dtls@v1.2.1/conn.go:159
github.com/pions/webrtc.(*DTLSTransport).Start(0xc0001df480, 0xc000160301, 0xc000061f38, 0x1, 0x1, 0x0, 0x0)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/dtlstransport.go:200 +0x489
github.com/pions/webrtc.(*PeerConnection).SetRemoteDescription.func2(0xc00007c200, 0xc0001b2160, 0xc000026c0a, 0x4, 0xc000270808, 0x18, 0xc00026608c, 0x7, 0xc000266094, 0x5f)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/peerconnection.go:848 +0x23d
created by github.com/pions/webrtc.(*PeerConnection).SetRemoteDescription
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/peerconnection.go:822 +0xd75

goroutine 9 [select]:
github.com/pions/dtls.(*Conn).startHandshakeOutbound.func1(0xc000268c00)
	/Users/lcurley/go/pkg/mod/github.com/pions/dtls@v1.2.1/conn.go:400 +0xd8
created by github.com/pions/dtls.(*Conn).startHandshakeOutbound
	/Users/lcurley/go/pkg/mod/github.com/pions/dtls@v1.2.1/conn.go:394 +0x3f

goroutine 10 [select]:
github.com/pions/webrtc/internal/mux.(*Endpoint).Read(0xc00000ec60, 0xc0002e6000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/Users/lcurley/go/pkg/mod/github.com/pions/webrtc@v1.2.1-0.20190304051543-15d0ae080844/internal/mux/endpoint.go:35 +0xd4
github.com/pions/dtls.createConn.func1(0xc000268c00)
	/Users/lcurley/go/pkg/mod/github.com/pions/dtls@v1.2.1/conn.go:129 +0xac
created by github.com/pions/dtls.createConn
	/Users/lcurley/go/pkg/mod/github.com/pions/dtls@v1.2.1/conn.go:122 +0x38f
```
